<a href="https://colab.research.google.com/github/Vanitha-1111-ART/AI_INTERNSHIP/blob/main/Association.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
d=pd.read_csv('/content/Market_Basket_Optimisation.csv',header=None)
d.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [ ]:
tr=[]
for i in range(0,len(d)):
  tr.append([str(d.values[i,j]) for j in range(0,20) if str(d.values[i,j])!='nan'])

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=d3a545e3c5cf30a0ae7883287c0c140455bc7a2ed4fe46444956418ef2945714
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
from apyori import apriori
rules=apriori(transactions=tr,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)
results=list(rules)
results

[RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'honey', 'fromage blanc'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)])]

In [ ]:
import pandas as pd

rows = []

for item in results:

    support = item.support

    for stat in item.ordered_statistics:

        rows.append({
            "LHS": ", ".join(list(stat.items_base)),
            "RHS": ", ".join(list(stat.items_add)),
            "Support": support,
            "Confidence": stat.confidence,
            "Lift": stat.lift
        })

df = pd.DataFrame(rows)

print(df)

                    LHS          RHS   Support  Confidence      Lift
0           light cream      chicken  0.004533    0.290598  4.843951
1  mushroom cream sauce     escalope  0.005733    0.300699  3.790833
2                 pasta     escalope  0.005866    0.372881  4.700812
3         fromage blanc        honey  0.003333    0.245098  5.164271
4         herb & pepper  ground beef  0.015998    0.323450  3.291994
5          tomato sauce  ground beef  0.005333    0.377358  3.840659
6           light cream    olive oil  0.003200    0.205128  3.114710
7     whole wheat pasta    olive oil  0.007999    0.271493  4.122410
8                 pasta       shrimp  0.005066    0.322034  4.506672

In [ ]:
df.sort_values('Lift')

                    LHS          RHS   Support  Confidence      Lift
6           light cream    olive oil  0.003200    0.205128  3.114710
4         herb & pepper  ground beef  0.015998    0.323450  3.291994
1  mushroom cream sauce     escalope  0.005733    0.300699  3.790833
5          tomato sauce  ground beef  0.005333    0.377358  3.840659
7     whole wheat pasta    olive oil  0.007999    0.271493  4.122410
8                 pasta       shrimp  0.005066    0.322034  4.506672
2                 pasta     escalope  0.005866    0.372881  4.700812
0           light cream      chicken  0.004533    0.290598  4.843951
3         fromage blanc        honey  0.003333    0.245098  5.164271

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules
import networkx as nx

**ECLAT**

In [ ]:
!pip install pyECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [ ]:
import pandas as pd
from pyECLAT import ECLAT

# dataset load
df = pd.read_csv("/content/Market_Basket_Optimisation.csv", header=None)
eclat = ECLAT(data=df)

indices, support = eclat.fit(min_support=0.03,
                             min_combination=1,
                             max_combination=3)

print(support)

Combination 1 by 1

36it [00:01, 28.34it/s]

Combination 2 by 2

630it [00:13, 47.32it/s]

Combination 3 by 3

7140it [02:27, 48.53it/s]

{'avocado': 0.03332888948140248, 'butter': 0.030129316091187842, 'burgers': 0.0871883748833489, 'frozen vegetables': 0.09532062391681109, 'cookies': 0.08038928142914278, 'cottage cheese': 0.03186241834422077, 'tomatoes': 0.06839088121583789, 'mineral water': 0.23836821757099053, 'low fat yogurt': 0.07652313024930009, 'green tea': 0.13211571790427942, 'chocolate': 0.1638448206905746, 'eggs': 0.17970937208372217, 'pancakes': 0.09505399280095987, 'fresh bread': 0.043060925209972005, 'cake': 0.08105585921877083, 'herb & pepper': 0.04946007199040128, 'cooking oil': 0.0510598586855086, 'escalope': 0.0793227569657379, 'chicken': 0.05999200106652446, 'salmon': 0.04252766297826956, 'ground beef': 0.09825356619117451, 'spaghetti': 0.17411011865084655, 'frozen smoothie': 0.06332489001466471, 'champagne': 0.04679376083188908, 'honey': 0.047460338621517134, 'shrimp': 0.07145713904812692, 'french fries': 0.1709105452606319, 'hot dogs': 0.03239568057592321, 'grated cheese': 0.0523930142647647, 'turkey': 0.06252499666711105, 'milk': 0.12958272230369283, 'olive oil': 0.0658578856152513, 'tomato juice': 0.030395947207039063, 'soup': 0.05052659645380616, 'whole wheat rice': 0.058525529929342755, 'brownies': 0.03372883615517931, 'frozen vegetables & mineral water': 0.03572856952406346, 'mineral water & green tea': 0.03106252499666711, 'mineral water & chocolate': 0.05265964538061592, 'mineral water & eggs': 0.05092654312758299, 'mineral water & pancakes': 0.03372883615517931, 'mineral water & ground beef': 0.040927876283162246, 'mineral water & spaghetti': 0.05972536995067324, 'mineral water & french fries': 0.03372883615517931, 'mineral water & milk': 0.04799360085321957, 'chocolate & eggs': 0.03319557392347687, 'chocolate & spaghetti': 0.03919477403012932, 'chocolate & french fries': 0.03439541394480736, 'chocolate & milk': 0.03212904946007199, 'eggs & spaghetti': 0.036528462871617116, 'eggs & french fries': 0.036395147313691506, 'eggs & milk': 0.03079589388081589, 'ground beef & spaghetti': 0.03919477403012932, 'spaghetti & milk': 0.03546193840821224}

In [ ]:
import pandas as pd
r=[]
for key,value in support.items():
  r.append(
      {
        "Items": key,
        "Support":value
      }
  )
df=pd.DataFrame(r)
print(df)

                                Items   Support
0                             avocado  0.033329
1                              butter  0.030129
2                             burgers  0.087188
3                   frozen vegetables  0.095321
4                             cookies  0.080389
5                      cottage cheese  0.031862
6                            tomatoes  0.068391
7                       mineral water  0.238368
8                      low fat yogurt  0.076523
9                           green tea  0.132116
10                          chocolate  0.163845
11                               eggs  0.179709
12                           pancakes  0.095054
13                        fresh bread  0.043061
14                               cake  0.081056
15                      herb & pepper  0.049460
16                        cooking oil  0.051060
17                           escalope  0.079323
18                            chicken  0.059992
19                             salmon  0.042528
20                        ground beef  0.098254
21                          spaghetti  0.174110
22                    frozen smoothie  0.063325
23                          champagne  0.046794
24                              honey  0.047460
25                             shrimp  0.071457
26                       french fries  0.170911
27                           hot dogs  0.032396
28                      grated cheese  0.052393
29                             turkey  0.062525
30                               milk  0.129583
31                          olive oil  0.065858
32                       tomato juice  0.030396
33                               soup  0.050527
34                   whole wheat rice  0.058526
35                           brownies  0.033729
36  frozen vegetables & mineral water  0.035729
37          mineral water & green tea  0.031063
38          mineral water & chocolate  0.052660
39               mineral water & eggs  0.050927
40           mineral water & pancakes  0.033729
41        mineral water & ground beef  0.040928
42          mineral water & spaghetti  0.059725
43       mineral water & french fries  0.033729
44               mineral water & milk  0.047994
45                   chocolate & eggs  0.033196
46              chocolate & spaghetti  0.039195
47           chocolate & french fries  0.034395
48                   chocolate & milk  0.032129
49                   eggs & spaghetti  0.036528
50                eggs & french fries  0.036395
51                        eggs & milk  0.030796
52            ground beef & spaghetti  0.039195
53                   spaghetti & milk  0.035462

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth,association_rules

# Load dataset
df = pd.read_csv("/content/Market_Basket_Optimisation.csv", header=None)

# Convert into transactions
transactions = []

for i in range(len(df)):
    transactions.append(
        [str(item) for item in df.iloc[i] if pd.notna(item)]
    )

te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

basket = pd.DataFrame(
    te_array,
    columns=te.columns_
)

# FP-Growth
fp = fpgrowth(
    basket,
    min_support=0.003,
    use_colnames=True
)

rules=associate_rules(

)

print(fp)

       support                       itemsets
0     0.238368                (mineral water)
1     0.132116                    (green tea)
2     0.076523               (low fat yogurt)
3     0.071457                       (shrimp)
4     0.065858                    (olive oil)
...        ...                            ...
1438  0.003733  (french fries, fromage blanc)
1439  0.003999          (fromage blanc, eggs)
1440  0.003733     (fromage blanc, spaghetti)
1441  0.003066         (flax seed, green tea)
1442  0.003466       (green beans, spaghetti)

[1443 rows x 2 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)